spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      name: alibabaDruidPool
      initial-size: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      #连接保持空闲而不被驱逐的最小时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 900000
      default-auto-commit: true
      #用来检测连接是否有效的sql
      validationQuery: SELECT 1
      #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      testWhileIdle: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnBorrow: false
      #开启web监控可视化
      stat-view-servlet:
        enabled: true
        allow: ""
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - com.alibaba.druid.spring.boot3.autoconfigure.DruidDataSourceAutoConfigure
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 1s
    socket-timeout: 30s
    jackson:
      serialization:
        indent-output: true
  ai:
    openai:
      api-key: sk-lAC9kwN0PsXfYB2e03B428F44266409bAe837f8f021b6245
      base-url: https://apikeyplus.com
      chat:
        options:
          model: gpt-3.5-turbo
#  data:
#    redis:
#      host: 127.0.0.1
#      port: 6379
#      password:
#      database: 0
mybatis-flex:
  datasource:
    mysql-datasource:
      type: ${spring.datasource.type}
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
      username: root
      password: root
    postgresql-datasource:
      type: ${spring.datasource.type}
      url: jdbc:postgresql://localhost:5432/talenthubDB
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: postgres
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    日志级别
logging:
  level:
    com.gxy.mapper: debug

openai:
  api:
    baseUrl: http://153.37.173.82:58002/v1/chat/completions
    model: qwen-turbo
    apiKey: sk-d910833e4e2f43f6967ca49117823506