server:
  port: 8081
spring:
  application:
    name: test-rabbitmq-producer
  rabbitmq:
    host: 106.15.65.113
    port: 5672
    username: rabbitmq
    password: rabbitmq123456..
    virtualHost: /